using System;
using System.Net;
using System.Net.Http;
using System.Threading;

namespace HoloQuestions
{
    public static class WebManager
    {
        public static bool UseAttempter { get; set; } = true;
        public static int AttemptsCount { get; set; } = 7;
        public static int AttemptsDelay { get; set; } = 12000;
        public static int StandartDelay { get; set; } = 400;

        private static readonly HttpClient httpClient = new HttpClient();
        private static readonly WebClient webClient = new WebClient();
        private static readonly Random random = new Random();

        private static long currentFile = 0;

        public static string GetRequest(string address)
        {
            string answer = GetRequest(new Uri(address));
            Thread.Sleep(StandartDelay);
            return answer;
        }

        private static string GetRequest(Uri uri, int attempt = 0)
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            string result = httpClient.GetAsync(uri).Result.Content.ReadAsStringAsync().Result;

            if (UseAttempter)
            {
                if (result.Contains("Retry later"))
                {
                    if (attempt < AttemptsCount)
                    {
                        attempt++;
                        Thread.Sleep(AttemptsDelay);
                        return GetRequest(uri, attempt);
                    }  
                    else throw new Exception("Слишком частые запросы к API!");
                }
            }

            return result;
        }

        public static void FilenameToMedianame(string path, string extension, out string medianame, out string mediapath)
        {
            medianame = $"media{currentFile}{extension}";
            mediapath = $"{path}{medianame}";
            currentFile++;
        }

        ///Path generated by FilenameToMedianame()
        public static void DownloadFile(string url, string path)
        {
            webClient.DownloadFile(url, path);
        }
    }
}
